const characters = [
  {
    name: "Walter White",
    universe: "Breaking Bad",
    role: "Anti-hero",
    skill: "Chemistry and manipulation",
    rating: 9,
    status: "DEAD",
    imageUrl: "/images/Walter_White_S5B.png",
    description: "A chemistry teacher turned drug lord.",
  },
  {
    name: "Geralt of Rivia",
    universe: "The Witcher",
    role: "Hero",
    skill: "Swordsmanship and magic signs",
    rating: 8,
    status: "ALIVE",
    imageUrl: "/images/geralt.jpg",
    description: "A monster hunter for hire, navigating a morally grey world.",
  },
  {
    name: "Tony Stark",
    universe: "Marvel Cinematic Universe",
    role: "Hero",
    skill: "Engineering and tactical genius",
    rating: 9,
    status: "DEAD",
    imageUrl: "/images/Robert_Downey,_Jr._2012.jpg",
    description: "A billionaire genius who builds powered armor suits.",
  },
  {
    name: "Arya Stark",
    universe: "Game of Thrones",
    role: "Assassin",
    skill: "Stealth and swordsmanship",
    rating: 8,
    status: "ALIVE",
    imageUrl: "/images/Arya_Stark.jpg",
    description: "A young noble who becomes a skilled and feared assassin.",
  },
  {
    name: "Light Yagami",
    universe: "Death Note",
    role: "Anti-hero",
    skill: "Strategic thinking and manipulation",
    rating: 7,
    status: "DEAD",
    imageUrl: "/images/Light_from_Death_Note.jpg",
    description: "A brilliant student who gains the power to kill with a notebook.",
  },
  {
    name: "Eleven",
    universe: "Stranger Things",
    role: "Hero",
    skill: "Telekinesis and psychic abilities",
    rating: 8,
    status: "ALIVE",
    imageUrl: "/images/Eleven_(Stranger_Things).jpg",
    description: "A girl with psychokinetic powers escaping a secret lab.",
  },
];

export default characters;